### ISSUE TITLE
Bug: Adapter does not fail a job with "Out of memory" errors

### ISSUE THREAD

**Issue by karthikbekalp** [aws-deadline/deadline-cloud-for-cinema-4d#66]
### Expected Behaviour

If rendering fails, we expect that the task is in FAILED status. 

### Current Behaviour

If rendering using Redshift fails with "Rendering failed: Out of memory", the job is classified as SUCCEEDED. 

### Reproduction Steps

I submitted a Redshift job to a Windows CMF instance with low GPU memory.  
[BYOLFarm_BYOL-Windows-Queue_session-c1f3baa0741f445dbae0dda6c85befa6.log](https://github.com/user-attachments/files/17263485/BYOLFarm_BYOL-Windows-Queue_session-c1f3baa0741f445dbae0dda6c85befa6.log)

### Code Snippet

I assume that this should be similar to effort for https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/issues/51. I wonder if there is a way to generalize this so that all types of Cinema 4D failures result in tasks getting failed?

**Comment by yuanmich2** [comment]
Just ran into this issue today. For me, the job never failed or completed, it just froze. on this error:
```
2024/10/07 15:16:21-07:00 ADAPTOR_OUTPUT: STDOUT: Rendering frame 0 at <Mon Oct  7 22:16:21 2024>
2024/10/07 15:16:30-07:00 ADAPTOR_OUTPUT: STDOUT: Error: RenderDocument: 1
```

The error gets printed on these few lines:
https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/blob/01a7c3f935d3a47a50745dff9f7e726dc1d69c61/src/deadline/cinema4d_adaptor/Cinema4DClient/cinema4d_handler.py#L71-L74

Digging a bit deeper, I found that error code `1` comes from `c4d.RENDERRESULT_OUTOFMEMORY` which is what took me to this github issue.

There's actually a large number of possible errors that we are not checking for at that spot in the code. A more complete list is here: https://developers.maxon.net/docs/py/2024_0_0a/consts/RENDERRESULT.html

**Comment by yuanmich2** [comment]
This is kind of off topic, but, in my case, the "Out of memory" error was actually caused by a licensing issue. I fixed it for my c7i.2xlarge Windows CMF machine by just setting the `redshift_LICENSE` environment variable to point to `port@host` for the port and hostname of my license server.

Either way, we need better error handling, but I just want to call out that this specific error could actually be a licensing thing.

**Comment by loachri** [comment]
For posterity, we should be mindful that "Out of memory" is an umbrella error message for many issues in C4D. While licensing configuration could lead to this error, we should be mindful that this error doesn't implicitly mean that there is a licensing issue. We recently saw this message again due to some issue completely separate from licensing
